# Generated by Django 5.1.7 on 2025-03-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='books.book')),
            ],
        ),
    ]
